toml[build]
  command = "npm run build"
  publish = "build"  # Change this to "dist" if you're using Vite

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"